; MONOPAT.INC - Graustufen-Raster fuer Mono-DMV je Farbe (Bayer 8x8), Bit 7 = links
        db 000h,000h,000h,000h,000h,000h,000h,000h   ; Farbe 0
        db 0AAh,044h,0AAh,000h,0AAh,004h,0AAh,000h   ; Farbe 1
        db 0EEh,055h,0BAh,055h,0EEh,055h,0ABh,055h   ; Farbe 2
        db 0FFh,0FDh,0FFh,077h,0FFh,0DDh,0FFh,077h   ; Farbe 3
        db 088h,000h,022h,000h,088h,000h,002h,000h   ; Farbe 4
        db 0AAh,054h,0AAh,011h,0AAh,045h,0AAh,011h   ; Farbe 5
        db 0FFh,055h,0FBh,055h,0FFh,055h,0BBh,055h   ; Farbe 6
        db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh   ; Farbe 7
